//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cti.Seller.WebTemplate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cti.Seller.WebTemplate.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Date.
        /// </summary>
        public static string Activity_Date {
            get {
                return ResourceManager.GetString("Activity_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Description.
        /// </summary>
        public static string ActivityDescription {
            get {
                return ResourceManager.GetString("ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Details.
        /// </summary>
        public static string ActivityDetails {
            get {
                return ResourceManager.GetString("ActivityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity.
        /// </summary>
        public static string AddActivity {
            get {
                return ResourceManager.GetString("AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lead.
        /// </summary>
        public static string AddLead {
            get {
                return ResourceManager.GetString("AddLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem adding the lead.  Please check your input and try again.  If the problem persists, please report to the system administrator..
        /// </summary>
        public static string AddLeadError {
            get {
                return ResourceManager.GetString("AddLeadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Lead Successfuly Saved.
        /// </summary>
        public static string AddLeadSuccess {
            get {
                return ResourceManager.GetString("AddLeadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Offer.
        /// </summary>
        public static string AddOffer {
            get {
                return ResourceManager.GetString("AddOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{{&quot;LeadID&quot;:&quot;{0}&quot;,&quot;Status&quot;:&quot;{1}&quot;}}}}.
        /// </summary>
        public static string AuditLogUpdateStatus {
            get {
                return ResourceManager.GetString("AuditLogUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Prospect.
        /// </summary>
        public static string BulkAction1 {
            get {
                return ResourceManager.GetString("BulkAction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Assign.
        /// </summary>
        public static string BulkAction2 {
            get {
                return ResourceManager.GetString("BulkAction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Lead.
        /// </summary>
        public static string BulkAction3 {
            get {
                return ResourceManager.GetString("BulkAction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliend Feedback.
        /// </summary>
        public static string ClientFeedBack {
            get {
                return ResourceManager.GetString("ClientFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed Schedule.
        /// </summary>
        public static string ClientFeedback1 {
            get {
                return ResourceManager.GetString("ClientFeedback1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Booking.
        /// </summary>
        public static string ClientFeedback2 {
            get {
                return ResourceManager.GetString("ClientFeedback2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interested.
        /// </summary>
        public static string ClientFeedback3 {
            get {
                return ResourceManager.GetString("ClientFeedback3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Decided.
        /// </summary>
        public static string ClientFeedback4 {
            get {
                return ResourceManager.GetString("ClientFeedback4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Interested.
        /// </summary>
        public static string ClientFeedback5 {
            get {
                return ResourceManager.GetString("ClientFeedback5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Town.
        /// </summary>
        public static string ClientFeedback6 {
            get {
                return ResourceManager.GetString("ClientFeedback6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescheduled Appointment.
        /// </summary>
        public static string ClientFeedback7 {
            get {
                return ResourceManager.GetString("ClientFeedback7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewing Payment Terms.
        /// </summary>
        public static string ClientFeedback8 {
            get {
                return ResourceManager.GetString("ClientFeedback8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Contact.
        /// </summary>
        public static string ClientFeedback9 {
            get {
                return ResourceManager.GetString("ClientFeedback9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Converting the Lead(s) to Prospect(s).
        /// </summary>
        public static string ConversionToProspectError {
            get {
                return ResourceManager.GetString("ConversionToProspectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Converted Lead(s) to Prospect(s).
        /// </summary>
        public static string ConversionToProspectSuccess {
            get {
                return ResourceManager.GetString("ConversionToProspectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownLine.
        /// </summary>
        public static string DownLine {
            get {
                return ResourceManager.GetString("DownLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Lead.
        /// </summary>
        public static string EditLead {
            get {
                return ResourceManager.GetString("EditLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be 10 to 30 characters long..
        /// </summary>
        public static string FieldMustBe10To30Chars {
            get {
                return ResourceManager.GetString("FieldMustBe10To30Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be 2 to 30 characters long..
        /// </summary>
        public static string FieldMustBe2To30Chars {
            get {
                return ResourceManager.GetString("FieldMustBe2To30Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be 5 to 15 characters long..
        /// </summary>
        public static string FieldMustBe5To15Chars {
            get {
                return ResourceManager.GetString("FieldMustBe5To15Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be 5 to 255 characters long..
        /// </summary>
        public static string FieldMustBe5To255Chars {
            get {
                return ResourceManager.GetString("FieldMustBe5To255Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be alphanumeric..
        /// </summary>
        public static string FieldMustBeAlphanumeric {
            get {
                return ResourceManager.GetString("FieldMustBeAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be numeric..
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid email address..
        /// </summary>
        public static string FieldMustBeValidEmail {
            get {
                return ResourceManager.GetString("FieldMustBeValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than 0..
        /// </summary>
        public static string FieldsMustBeGreaterThan0 {
            get {
                return ResourceManager.GetString("FieldsMustBeGreaterThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid contact number..
        /// </summary>
        public static string FieldsMustBeValidContactNo {
            get {
                return ResourceManager.GetString("FieldsMustBeValidContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not exceed 100 characters long..
        /// </summary>
        public static string FieldsMustNotExceed100Chars {
            get {
                return ResourceManager.GetString("FieldsMustNotExceed100Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not exceed 15 characters long..
        /// </summary>
        public static string FieldsMustNotExceed15Chars {
            get {
                return ResourceManager.GetString("FieldsMustNotExceed15Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not exceed 30 characters long..
        /// </summary>
        public static string FieldsMustNotExceed30Chars {
            get {
                return ResourceManager.GetString("FieldsMustNotExceed30Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not exceed 50 characters long..
        /// </summary>
        public static string FieldsMustNotExceed50Chars {
            get {
                return ResourceManager.GetString("FieldsMustNotExceed50Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check for incomplete or invalid fields..
        /// </summary>
        public static string IncompleteOrInvalidFields {
            get {
                return ResourceManager.GetString("IncompleteOrInvalidFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landline No..
        /// </summary>
        public static string LandlineNo {
            get {
                return ResourceManager.GetString("LandlineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Aging.
        /// </summary>
        public static string LeadAging {
            get {
                return ResourceManager.GetString("LeadAging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead ID.
        /// </summary>
        public static string LeadID {
            get {
                return ResourceManager.GetString("LeadID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Information.
        /// </summary>
        public static string LeadInformation {
            get {
                return ResourceManager.GetString("LeadInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LeadName {
            get {
                return ResourceManager.GetString("LeadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leads.
        /// </summary>
        public static string Leads {
            get {
                return ResourceManager.GetString("Leads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leads Listing.
        /// </summary>
        public static string LeadsListing {
            get {
                return ResourceManager.GetString("LeadsListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Source.
        /// </summary>
        public static string LeadSource {
            get {
                return ResourceManager.GetString("LeadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Upline.
        /// </summary>
        public static string LeadSource1 {
            get {
                return ResourceManager.GetString("LeadSource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMC.
        /// </summary>
        public static string LeadSource2 {
            get {
                return ResourceManager.GetString("LeadSource2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster.
        /// </summary>
        public static string LeadSource3 {
            get {
                return ResourceManager.GetString("LeadSource3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Sourced.
        /// </summary>
        public static string LeadSource4 {
            get {
                return ResourceManager.GetString("LeadSource4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referrals.
        /// </summary>
        public static string LeadSource5 {
            get {
                return ResourceManager.GetString("LeadSource5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Status.
        /// </summary>
        public static string LeadStatus {
            get {
                return ResourceManager.GetString("LeadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        public static string LeadStatus1 {
            get {
                return ResourceManager.GetString("LeadStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Conversion To Prospect.
        /// </summary>
        public static string LeadStatus2 {
            get {
                return ResourceManager.GetString("LeadStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospect.
        /// </summary>
        public static string LeadStatus3 {
            get {
                return ResourceManager.GetString("LeadStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junk/Bad Lead.
        /// </summary>
        public static string LeadStatus4 {
            get {
                return ResourceManager.GetString("LeadStatus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Meeting.
        /// </summary>
        public static string LeadTask1 {
            get {
                return ResourceManager.GetString("LeadTask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tripping.
        /// </summary>
        public static string LeadTask2 {
            get {
                return ResourceManager.GetString("LeadTask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation.
        /// </summary>
        public static string LeadTask3 {
            get {
                return ResourceManager.GetString("LeadTask3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string LeadTask4 {
            get {
                return ResourceManager.GetString("LeadTask4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followup Meeting.
        /// </summary>
        public static string LeadTask5 {
            get {
                return ResourceManager.GetString("LeadTask5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followup Tripping.
        /// </summary>
        public static string LeadTask6 {
            get {
                return ResourceManager.GetString("LeadTask6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followup Presentation.
        /// </summary>
        public static string LeadTask7 {
            get {
                return ResourceManager.GetString("LeadTask7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followup Requirements.
        /// </summary>
        public static string LeadTask8 {
            get {
                return ResourceManager.GetString("LeadTask8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Touchpoint.
        /// </summary>
        public static string LeadTouchpoint {
            get {
                return ResourceManager.GetString("LeadTouchpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhibit.
        /// </summary>
        public static string LeadTouchPoint1 {
            get {
                return ResourceManager.GetString("LeadTouchPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open House.
        /// </summary>
        public static string LeadTouchPoint2 {
            get {
                return ResourceManager.GetString("LeadTouchPoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Unit.
        /// </summary>
        public static string LeadTouchPoint3 {
            get {
                return ResourceManager.GetString("LeadTouchPoint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarketingOffice.
        /// </summary>
        public static string LeadTouchPoint4 {
            get {
                return ResourceManager.GetString("LeadTouchPoint4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMC.
        /// </summary>
        public static string LeadTouchPoint5 {
            get {
                return ResourceManager.GetString("LeadTouchPoint5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnSite.
        /// </summary>
        public static string LeadTouchPoint6 {
            get {
                return ResourceManager.GetString("LeadTouchPoint6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        public static string LeadTouchPoint7 {
            get {
                return ResourceManager.GetString("LeadTouchPoint7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No..
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Lead.
        /// </summary>
        public static string NewLead {
            get {
                return ResourceManager.GetString("NewLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Lead Status.
        /// </summary>
        public static string NewLeadStatus {
            get {
                return ResourceManager.GetString("NewLeadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected Lead(s) for Converstion to Propect(s)..
        /// </summary>
        public static string NoSelectedForConversionToProspect {
            get {
                return ResourceManager.GetString("NoSelectedForConversionToProspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one record.
        /// </summary>
        public static string NoSelectedItem {
            get {
                return ResourceManager.GetString("NoSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Offered.
        /// </summary>
        public static string OfferDate {
            get {
                return ResourceManager.GetString("OfferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Information.
        /// </summary>
        public static string OfferInformation {
            get {
                return ResourceManager.GetString("OfferInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold - 0%.
        /// </summary>
        public static string OfferingProbability1 {
            get {
                return ResourceManager.GetString("OfferingProbability1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm - 50%.
        /// </summary>
        public static string OfferingProbability2 {
            get {
                return ResourceManager.GetString("OfferingProbability2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot - 90%.
        /// </summary>
        public static string OfferingProbability3 {
            get {
                return ResourceManager.GetString("OfferingProbability3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With RF - 100%.
        /// </summary>
        public static string OfferingProbability4 {
            get {
                return ResourceManager.GetString("OfferingProbability4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offerings.
        /// </summary>
        public static string Offerings {
            get {
                return ResourceManager.GetString("Offerings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Code.
        /// </summary>
        public static string PositionCode {
            get {
                return ResourceManager.GetString("PositionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability.
        /// </summary>
        public static string Probability {
            get {
                return ResourceManager.GetString("Probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospects.
        /// </summary>
        public static string Prospects {
            get {
                return ResourceManager.GetString("Prospects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Fee No..
        /// </summary>
        public static string ReserveFeeNo {
            get {
                return ResourceManager.GetString("ReserveFeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving your record..
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add this lead?.
        /// </summary>
        public static string SaveLeadConfirmation {
            get {
                return ResourceManager.GetString("SaveLeadConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record was successfully saved..
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Event.
        /// </summary>
        public static string ScheduleEvent {
            get {
                return ResourceManager.GetString("ScheduleEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SellerName {
            get {
                return ResourceManager.GetString("SellerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House No./ Street / Village / Barangay.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspects.
        /// </summary>
        public static string Suspects {
            get {
                return ResourceManager.GetString("Suspects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Dropdown.
        /// </summary>
        public static string ToggleDropdown {
            get {
                return ResourceManager.GetString("ToggleDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconverted.
        /// </summary>
        public static string UnconvertedLeads {
            get {
                return ResourceManager.GetString("UnconvertedLeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Amount.
        /// </summary>
        public static string UnitAmount {
            get {
                return ResourceManager.GetString("UnitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit No..
        /// </summary>
        public static string UnitNo {
            get {
                return ResourceManager.GetString("UnitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Offered.
        /// </summary>
        public static string UnitsOffered {
            get {
                return ResourceManager.GetString("UnitsOffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update this record?.
        /// </summary>
        public static string UpdateConfirmation {
            get {
                return ResourceManager.GetString("UpdateConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated .
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Edit.
        /// </summary>
        public static string ViewEdit {
            get {
                return ResourceManager.GetString("ViewEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
    }
}
